language: clojure
lein: 2.8.3
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsodium18
jdk:
  -openjdk8
script: lein do cljfmt check, eastwood, test
deploy:
  provider: script
  skip_cleanup: true
  script: lein deploy
  on:
    tags: true
cache:
  directories:
    - $HOME/.m2
